### ISSUE TITLE
Google Play: Landroid/view/WindowInsets$Type;-><init>()V

### ISSUE THREAD

**Issue by kazuser** [viniciusfbb/fmx_tutorials#5]
Vinícius, hi!

Is it possible to fix it?

Google Play console > App > Testing > Pre-launch report > Details:
![изображение](https://user-images.githubusercontent.com/3335273/129464847-057ad48e-53c9-4c22-b9ff-1640973d0f15.png)

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/WindowInsets$Type;-><init>()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at com.embarcadero.rtl.ProxyInterface.dispatchToNative(Native Method)
	at com.embarcadero.rtl.ProxyInterface.invoke(ProxyInterface.java:21)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy19.onLayoutChange(Unknown Source)
	at android.view.View.layout(View.java:22862)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
	at android.view.View.layout(View.java:22844)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by viniciusfbb** [comment]
I published a new [system bars class](https://github.com/viniciusfbb/fmx_tutorials/tree/master/delphi_system_bars)
Can you test with the new class? If the error persists, you need to send me more informations, like dvice model, android version and delphi version.

**Comment by kazuser** [comment]
Ok, thanks! Give me 2-3 days, please)

**Comment by kazuser** [comment]
It's ok now in Google Play! Thank you! :)
